In [121]:
a = np.array(range(30))
b = a.reshape((5, 6))
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [127]:
c = b.ravel(order='F')
c

array([ 0,  6, 12, 18, 24,  1,  7, 13, 19, 25,  2,  8, 14, 20, 26,  3,  9,
       15, 21, 27,  4, 10, 16, 22, 28,  5, 11, 17, 23, 29])

In [129]:
d = c.reshape((5,6))
d

array([[ 0,  6, 12, 18, 24,  1],
       [ 7, 13, 19, 25,  2,  8],
       [14, 20, 26,  3,  9, 15],
       [21, 27,  4, 10, 16, 22],
       [28,  5, 11, 17, 23, 29]])

In [136]:
e = np.sort(d, axis=0)
e

array([[ 0,  5,  4,  3,  2,  1],
       [ 7,  6, 11, 10,  9,  8],
       [14, 13, 12, 17, 16, 15],
       [21, 20, 19, 18, 23, 22],
       [28, 27, 26, 25, 24, 29]])

In [144]:
np.where(e%6==1)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))